name: noScribe
channels:
  - conda-forge
  - defaults

dependencies:
  - python<3.9
  - tk
  - pillow
  - pyyaml
  - appdirs
  - typing
  - pathlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - pip:
    - customtkinter
    - elevate
    # - cpufeature
    - python-i18n
    - git+https://github.com/kaixxx/python-docx
    - git+https://github.com/kaixxx/pyannote-audio