"""Ephemeral storage safeguards for uploaded audio."""

from __future__ import annotations

import os
from pathlib import Path


def prepare_runtime_directory(path: Path, *, require_tmpfs: bool) -> None:
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    try:
        path.chmod(0o700)
    except OSError:
        if os.name != "nt":
            raise
    if require_tmpfs and not _is_on_linux_memory_filesystem(path):
        raise RuntimeError(
            f"Server runtime directory {path} is not on tmpfs or ramfs."
        )
    cleanup_stale_audio(path)


def cleanup_stale_audio(path: Path) -> None:
    """Remove only private files whose names are generated by this server."""
    for pattern in ("upload-*.flac", "upload-*.wav"):
        for candidate in path.glob(pattern):
            if candidate.is_file() and not candidate.is_symlink():
                candidate.unlink(missing_ok=True)


def _is_on_linux_memory_filesystem(path: Path) -> bool:
    mountinfo = Path("/proc/self/mountinfo")
    if os.name == "nt" or not mountinfo.is_file():
        return False
    resolved = path.resolve()
    matches: list[tuple[int, str]] = []
    try:
        for line in mountinfo.read_text(encoding="utf-8").splitlines():
            before, after = line.split(" - ", 1)
            fields = before.split()
            fs_type = after.split()[0]
            mount_point = Path(fields[4].replace("\\040", " ")).resolve()
            try:
                resolved.relative_to(mount_point)
            except ValueError:
                continue
            matches.append((len(mount_point.parts), fs_type))
    except (OSError, ValueError, IndexError):
        return False
    if not matches:
        return False
    return max(matches)[1] in {"tmpfs", "ramfs"}
