#!/bin/sh
# Regenerate docker/requirements.lock: resolve environments/requirements_linux.txt
# afresh (still honouring docker/constraints.txt) and record the resulting
# package set. Build and test the image afterwards before committing the new
# lock file.
set -eu
cd "$(dirname "$0")/.."

# The Dockerfile copies the lock file even when it is not applied.
[ -f docker/requirements.lock ] || : > docker/requirements.lock

docker build -f docker/Dockerfile --target deps --build-arg USE_LOCK=0 -t noscribe:relock .

{
  cat <<'HEADER'
# Generated by docker/update-lock.sh - do not edit by hand.
# Full set of Python packages in the tested image (pip freeze). The Dockerfile
# uses it as a constraints file and fails the build if the result differs.
HEADER
  docker run --rm noscribe:relock pip freeze --all | tr -d '\r' | grep -v '^pip=='
} > docker/requirements.lock.tmp
mv docker/requirements.lock.tmp docker/requirements.lock

echo "docker/requirements.lock updated:"
git --no-pager diff --stat -- docker/requirements.lock || true
